openapi: 3.0.3
info:
  contact:
    email: bayer@predic8.de
  description: Get a quote online
  title: Quotation API
  version: "1.0"
servers:
- url: https://rfq-server.azurewebsites.net/v1
tags:
- name: Quote
paths:
  /rfqs:
    post:
      description: Request a quote
      operationId: getQuote
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quotation'
      responses:
        "201":
          description: OK
      tags:
      - Quote
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: Quote
components:
  schemas:
    Quotation:
      example:
        mode: mode
        quantity: 80
        shipment: FOB
        price: 1.99
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        article: Firecracker
      properties:
        id:
          format: uuid
          type: string
        article:
          example: Firecracker
          maxLength: 20
          pattern: (\w+\W*)*
          type: string
        quantity:
          format: int32
          maximum: 1000
          minimum: 0
          type: integer
        price:
          example: 1.99
          minimum: 0
          type: number
        shipment:
          enum:
          - FOB
          - DAT
          type: string
        mode:
          maxLength: 3
          pattern: "[A-Z]{3}"
          type: string
      type: object
