name: Build and deploy JAR app to Azure Web App - rfq-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Build Maven
        run: mvn install
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: java-app

      - id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rfq-server'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7EE7C9AF968D4F45B1632C26ACEEB14E }}
          package: '*.jar'
